version: '3.9'

name: valhala

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1234
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    volumes:
      - /var/lib/docker/volumes/mssql_db/_data:/var/opt/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Password1234 -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

  db.configurator:
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./src/Resources:/docker-entrypoint-initdb.d
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P Password1234 -C -d master -i docker-entrypoint-initdb.d/Valhala.sql;
      echo "Created database Valhala";
      /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P Password1234 -C -d master -i docker-entrypoint-initdb.d/Povoamento.sql;
      echo "Populated database Valhala";
      echo "Done! ✅";
      '